/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArchivableContent } from './archivableContent';
import { DependencyTreeNode } from './dependencyTreeNode';
import { IdWithName } from './idWithName';


export interface Archivable {
    identifier?: IdWithName;
    archiveType?: Archivable.ArchiveTypeEnum;
    definition?: string;
    checksum?: string;
    contents?: Array<ArchivableContent>;
    outboundDependencies?: Array<DependencyTreeNode>;
    inboundDependencies?: Array<DependencyTreeNode>;
}
export namespace Archivable {
    export type ArchiveTypeEnum = 'explicit' | 'dependency';
    export const ArchiveTypeEnum = {
        Explicit: 'explicit' as ArchiveTypeEnum,
        Dependency: 'dependency' as ArchiveTypeEnum
    }
}
