/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ConditionValue} from './conditionValue';


export interface BooleanCondition {
	operator?: BooleanCondition.OperatorEnum;
	value?: ConditionValue;
}
export namespace BooleanCondition {
	export type OperatorEnum = 'isTrue' | 'isFalse' | 'equalTo' | 'notEqualTo';
	export const OperatorEnum = {
		IsTrue: 'isTrue' as OperatorEnum,
		IsFalse: 'isFalse' as OperatorEnum,
		EqualTo: 'equalTo' as OperatorEnum,
		NotEqualTo: 'notEqualTo' as OperatorEnum
	};
}
