/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ChartValue {
    value?: string;
    numberValue?: number;
    dateTimeValue?: string;
    type?: ChartValue.TypeEnum;
}
export namespace ChartValue {
    export type TypeEnum = 'string' | 'number' | 'boolean' | 'dateTime' | 'date' | 'time';
    export const TypeEnum = {
        String: 'string' as TypeEnum,
        Number: 'number' as TypeEnum,
        Boolean: 'boolean' as TypeEnum,
        DateTime: 'dateTime' as TypeEnum,
        Date: 'date' as TypeEnum,
        Time: 'time' as TypeEnum
    }
}
