/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ConditionGroupNode} from './conditionGroupNode';


export interface ConditionGroup {
	type?: ConditionGroup.TypeEnum;
	nodes?: Array<ConditionGroupNode>;
}

export namespace ConditionGroup {
	export type TypeEnum = 'and' | 'or';
	export const TypeEnum = {
		And: 'and' as TypeEnum,
		Or: 'or' as TypeEnum
	}
}
