/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ConditionType = 'date' | 'time' | 'dateTime' | 'number' | 'text' | 'boolean';

export const ConditionType = {
	Date: 'date' as ConditionType,
	Time: 'time' as ConditionType,
	DateTime: 'dateTime' as ConditionType,
	Number: 'number' as ConditionType,
	Text: 'text' as ConditionType,
	Boolean: 'boolean' as ConditionType
}
