/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ConditionValueType = 'nothing' | 'docProp' | 'constant' | 'field' | 'expression' | 'flowVariable';

export const ConditionValueType = {
    Nothing: 'nothing' as ConditionValueType,
    DocProp: 'docProp' as ConditionValueType,
    Constant: 'constant' as ConditionValueType,
    Field: 'field' as ConditionValueType,
    Expression: 'expression' as ConditionValueType,
    FlowVariable: 'flowVariable' as ConditionValueType
}
