/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ConnectorTypeResourceFetch} from './connectorTypeResourceFetch';


export interface ConnectorType {
	id?: string;
	displayName: string;
	description?: string;
	javaType?: string;
	readSchema?: any;
	writeSchema?: any;
	supportsLogin?: boolean;
	resourceFetch?: ConnectorTypeResourceFetch;
}
