/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {CounterDocuments} from './counterDocuments';


export interface Counter {
	window?: Counter.WindowEnum;
	start?: string;
	documents?: CounterDocuments;
	executions?: number;
}

export namespace Counter {
	export type WindowEnum = 'year' | 'month';
	export const WindowEnum = {
		Year: 'year' as WindowEnum,
		Month: 'month' as WindowEnum
	};
}
