/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {CustomContentFieldBoolean} from './customContentFieldBoolean';
import {CustomContentFieldData} from './customContentFieldData';
import {CustomContentFieldDateTime} from './customContentFieldDateTime';
import {CustomContentFieldEntityRef} from './customContentFieldEntityRef';
import {CustomContentFieldNumber} from './customContentFieldNumber';
import {CustomContentFieldOptionset} from './customContentFieldOptionset';
import {CustomContentFieldStringDefault} from './customContentFieldStringDefault';
import {CustomContentFieldText} from './customContentFieldText';


export interface CustomContentField {
	id?: string;
	displayName?: string;
	fieldName?: string;
	description?: string;
	type?: CustomContentField.TypeEnum;
	required?: boolean;
	repeating?: boolean;
	text?: CustomContentFieldText;
	multiLineText?: CustomContentFieldText;
	richText?: CustomContentFieldText;
	optionset?: CustomContentFieldOptionset;
	number?: CustomContentFieldNumber;
	boolean?: CustomContentFieldBoolean;
	entityRef?: CustomContentFieldEntityRef;
	data?: CustomContentFieldData;
	date?: CustomContentFieldStringDefault;
	time?: CustomContentFieldStringDefault;
	dateTime?: CustomContentFieldDateTime;
}
export namespace CustomContentField {
	export type TypeEnum = 'text' | 'multiLineText' | 'richText' | 'number' | 'boolean' | 'entityRef' | 'data' | 'date' | 'time' | 'dateTime' | 'optionset';
	export const TypeEnum = {
		Text: 'text' as TypeEnum,
		MultiLineText: 'multiLineText' as TypeEnum,
		RichText: 'richText' as TypeEnum,
		Number: 'number' as TypeEnum,
		Boolean: 'boolean' as TypeEnum,
		EntityRef: 'entityRef' as TypeEnum,
		Data: 'data' as TypeEnum,
		Date: 'date' as TypeEnum,
		Time: 'time' as TypeEnum,
		DateTime: 'dateTime' as TypeEnum,
		Optionset: 'optionset' as TypeEnum
	};
}
