/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DataReference} from './dataReference';
import {DataValue} from './dataValue';
import {FlowExecution} from './flowExecution';
import {IdWithName} from './idWithName';
import {ObjectUsage} from './objectUsage';


export interface Data {
	id?: string;
	displayName?: string;
	description?: string;
	createdAt?: string;
	createdBy?: IdWithName;
	modifiedAt?: string;
	modifiedBy?: IdWithName;
	dataset?: IdWithName;
	pluginDataset?: IdWithName;
	type?: Data.TypeEnum;
	value?: DataValue;
	reference?: DataReference;
	dataAvailable?: boolean;
	expiration?: string;
	usage?: ObjectUsage;
	flowExecution?: FlowExecution;
	contentType?: string;
}

export namespace Data {
	export type TypeEnum = 'reference' | 'value';
	export const TypeEnum = {
		Reference: 'reference' as TypeEnum,
		Value: 'value' as TypeEnum
	}
}
