/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DatasetExtendedContentDatasets} from './datasetExtendedContentDatasets';
import {DatasetExtendedContentFields} from './datasetExtendedContentFields';
import {DatasetExtendedContentRelations} from './datasetExtendedContentRelations';
import {DatasetExtendedContentViews} from './datasetExtendedContentViews';


export interface DatasetExtendedContent {
	name?: string;
	root?: string;
	datasets?: Array<DatasetExtendedContentDatasets>;
	relations?: Array<DatasetExtendedContentRelations>;
	fields?: Array<DatasetExtendedContentFields>;
	views?: Array<DatasetExtendedContentViews>;
}
