/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DatasetSchemaContent {
	wrapperElementName?: string;
	primaryEntity?: string;
	schemaContent?: string;
	schemaType?: DatasetSchemaContent.SchemaTypeEnum;
}

export namespace DatasetSchemaContent {
	export type SchemaTypeEnum = 'xsd';
	export const SchemaTypeEnum = {
		Xsd: 'xsd' as SchemaTypeEnum
	}
}
