/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DatasetStandardContentQueries} from './datasetStandardContentQueries';
import {EntityReference} from './entityReference';


export interface DatasetStandardContent {
	wrapperElementName?: string;
	primaryEntity?: string;
	allowedTypesOfData?: Array<DatasetStandardContent.AllowedTypesOfDataEnum>;
	entities?: Array<EntityReference>;
	queries?: DatasetStandardContentQueries;
}
export namespace DatasetStandardContent {
	export type AllowedTypesOfDataEnum = 'value' | 'reference';
	export const AllowedTypesOfDataEnum = {
		Value: 'value' as AllowedTypesOfDataEnum,
		Reference: 'reference' as AllowedTypesOfDataEnum
	};
}
