/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {EntityDefinition} from './entityDefinition';
import {IdWithName} from './idWithName';


export interface DatasourceLayout {
	datasourceType?: IdWithName;
	type?: DatasourceLayout.TypeEnum;
	entities?: Array<EntityDefinition>;
}
export namespace DatasourceLayout {
	export type TypeEnum = 'hierarchical' | 'relational';
	export const TypeEnum = {
		Hierarchical: 'hierarchical' as TypeEnum,
		Relational: 'relational' as TypeEnum
	};
}
