/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DateFormatStyle = 'full' | 'long' | 'medium' | 'short' | 'unspecified';

export const DateFormatStyle = {
	Full: 'full' as DateFormatStyle,
	Long: 'long' as DateFormatStyle,
	Medium: 'medium' as DateFormatStyle,
	Short: 'short' as DateFormatStyle,
	Unspecified: 'unspecified' as DateFormatStyle
}
