/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdWithName } from './idWithName';


export interface DependencyTreeNode {
    target?: IdWithName;
    loaded?: DependencyTreeNode.LoadedEnum;
    children?: Array<DependencyTreeNode>;
}
export namespace DependencyTreeNode {
    export type LoadedEnum = 'eager' | 'lazy';
    export const LoadedEnum = {
        Eager: 'eager' as LoadedEnum,
        Lazy: 'lazy' as LoadedEnum
    }
}
