/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DependencyDirection = 'inbound' | 'outbound' | 'both';

export const DependencyDirection = {
	Inbound: 'inbound' as DependencyDirection,
	Outbound: 'outbound' as DependencyDirection,
	Both: 'both' as DependencyDirection
}
