/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DocGenSettingsDatas} from './docGenSettingsDatas';
import {DocGenSettingsResult} from './docGenSettingsResult';
import {DocGenSettingsTemplate} from './docGenSettingsTemplate';
import {ObjectReference} from './objectReference';


export interface DocGenSettings {
	language?: string;
	templateRef?: ObjectReference;
	template?: DocGenSettingsTemplate;
	dataRefs?: Array<ObjectReference>;
	datas?: Array<DocGenSettingsDatas>;
	result?: DocGenSettingsResult;
}
