/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DocGenSettingsResultPdfEncryption} from './docGenSettingsResultPdfEncryption';


export interface DocGenSettingsResultPdf {
	/**
	 * Specifies the PDF standards compliance level. Pdf15: The output file will comply with the PDF 1.5 standard. PdfA1a: The output file will comply with the PDF/A-1a standard. This level includes all the requirements of PDF/A-1b and additionally requires that document structure be included (also known as being tagged), with the objective of ensuring that document content can be searched and repurposed. PdfA1b: The output file will comply with the PDF/A-1b standard. PDF/A-1b has the objective of ensuring reliable reproduction of the visual appearance of the document
	 */
	compliance?: DocGenSettingsResultPdf.ComplianceEnum;
	/**
	 * Specifies whether to preserve form fields in PDF or convert them to text. Microsoft Word form fields include text input, drop down and check box controls. When set to false, these fields will be exported as text. When set to true, these fields will be exported as PDF form fields. When exporting form fields to PDF as form fields, some formatting loss might occur because PDF form fields do not support all features of Microsoft Word form fields
	 */
	preserveFormFields?: boolean;
	/**
	 * Controls how fonts are embedded into the resulting PDF documents. All: Embed all fonts. Non Standard: embed all fonts except standard Windows fonts Arial and Times New Roman. None: no fonts are embedded
	 */
	fontEmbeddingMode?: DocGenSettingsResultPdf.FontEmbeddingModeEnum;
	encryption?: DocGenSettingsResultPdfEncryption;
}
export namespace DocGenSettingsResultPdf {
	export type ComplianceEnum = 'pdf15' | 'pdfA1b' | 'pdfA1a';
	export const ComplianceEnum = {
		Pdf15: 'pdf15' as ComplianceEnum,
		PdfA1b: 'pdfA1b' as ComplianceEnum,
		PdfA1a: 'pdfA1a' as ComplianceEnum
	};
	export type FontEmbeddingModeEnum = 'all' | 'nonStandard' | 'none';
	export const FontEmbeddingModeEnum = {
		All: 'all' as FontEmbeddingModeEnum,
		NonStandard: 'nonStandard' as FontEmbeddingModeEnum,
		None: 'none' as FontEmbeddingModeEnum
	};
}
