/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocGenSettingsResultOoxml {
	format?: DocGenSettingsResultOoxml.FormatEnum;
	password?: string;
	compliance?: DocGenSettingsResultOoxml.ComplianceEnum;
}
export namespace DocGenSettingsResultOoxml {
	export type FormatEnum = 'docx' | 'dotx' | 'docm' | 'dotm' | 'flatopc';
	export const FormatEnum = {
		Docx: 'docx' as FormatEnum,
		Dotx: 'dotx' as FormatEnum,
		Docm: 'docm' as FormatEnum,
		Dotm: 'dotm' as FormatEnum,
		Flatopc: 'flatopc' as FormatEnum
	};
	export type ComplianceEnum = 'iso_29500_2008_strict' | 'ecma_376_2006' | 'iso_29500_2008_transitional';
	export const ComplianceEnum = {
		Iso295002008Strict: 'iso_29500_2008_strict' as ComplianceEnum,
		Ecma3762006: 'ecma_376_2006' as ComplianceEnum,
		Iso295002008Transitional: 'iso_29500_2008_transitional' as ComplianceEnum
	};
}
