/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocGenSettingsResultHtml {
	format?: DocGenSettingsResultHtml.FormatEnum;
	/**
	 * Specifies the encoding to use
	 */
	encoding?: string;
	/**
	 * Specifies how headers and footers are output. None: Headers and footers are not exported. PerSection: Primary headers and footers are exported at the beginning and the end of each section. FirstSectionHeaderLastSectionFooter: Primary header of the first section is exported at the beginning of the document and primary footer is at the end. FirstPageheaderFooterPerSection: First page header and footer are exported at the beginning and the end of each section.
	 */
	exportHeadersFooters?: DocGenSettingsResultHtml.ExportHeadersFootersEnum;
	/**
	 * Specifies whether page margins is exported
	 */
	exportPageMargins?: boolean;
	/**
	 * Specifies whether page setup is exported
	 */
	exportPageSetup?: boolean;
	/**
	 * Specifies whether to write page numbers to table of contents
	 */
	exportTOCPageNumbers?: boolean;
	/**
	 * Specifies whether font sizes should be output in relative units
	 */
	exportRelativeFontSize?: boolean;
	/**
	 * Specifies the output resolution for images in dpi
	 */
	imageResolution?: number;
	/**
	 * Specifies whether images are saved in Base64
	 */
	exportImagesAsBase64?: boolean;
	/**
	 * Specifies whether original URL should be used as the URL of the linked images
	 */
	maintainLinkToExternalImages?: boolean;
	/**
	 * Specifies whether images are scaled to the bounding shape size when exporting
	 */
	scaleImagesToShapeSize?: boolean;
}

export namespace DocGenSettingsResultHtml {
	export type FormatEnum = 'epub' | 'mhtml' | 'html';
	export const FormatEnum = {
		Epub: 'epub' as FormatEnum,
		Mhtml: 'mhtml' as FormatEnum,
		Html: 'html' as FormatEnum
	}
	export type ExportHeadersFootersEnum =
		'firstPageheaderFooterPerSection'
		| 'perSection'
		| 'firstSectionHeaderLastSectionFooter'
		| 'none';
	export const ExportHeadersFootersEnum = {
		FirstPageheaderFooterPerSection: 'firstPageheaderFooterPerSection' as ExportHeadersFootersEnum,
		PerSection: 'perSection' as ExportHeadersFootersEnum,
		FirstSectionHeaderLastSectionFooter: 'firstSectionHeaderLastSectionFooter' as ExportHeadersFootersEnum,
		None: 'none' as ExportHeadersFootersEnum
	}
}
