/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocGenSettingsResultOdt {
	/**
	 * Either ODT or OTT
	 */
	format?: DocGenSettingsResultOdt.FormatEnum;
	/**
	 * Specifies whether export should correspond to ODT specification 1.1 strictly. OOo 3.0 displays files correctly when they contain elements and attributes of ODT 1.2. Use false for this purpose, or true for strict conformity of specification 1.1
	 */
	isStrictSchema11?: boolean;
}

export namespace DocGenSettingsResultOdt {
	export type FormatEnum = 'odt' | 'ott';
	export const FormatEnum = {
		Odt: 'odt' as FormatEnum,
		Ott: 'ott' as FormatEnum
	}
}
