/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocGenSettingsResultPdfEncryption {
	/**
	 * The encryption algorithm. rc4_40: RC4 encryption, key length of 40 bits. rc4_128: RC4 encryption, key length of 128 bits.
	 */
	algorithm?: DocGenSettingsResultPdfEncryption.AlgorithmEnum;
	/**
	 * The password for the encrypted document
	 */
	ownerPassword?: string;
	/**
	 * The password required for opening the encrypted document
	 */
	userPassword?: string;
	permissions?: Array<DocGenSettingsResultPdfEncryption.PermissionsEnum>;
}

export namespace DocGenSettingsResultPdfEncryption {
	export type AlgorithmEnum = 'rc4_128' | 'rc4_40';
	export const AlgorithmEnum = {
		_128: 'rc4_128' as AlgorithmEnum,
		_40: 'rc4_40' as AlgorithmEnum
	}
	export type PermissionsEnum =
		'disallowAll'
		| 'allowAll'
		| 'contentCopy'
		| 'contentCopyForAccessibility'
		| 'modifyContents'
		| 'modifyAnnotations'
		| 'fillIn'
		| 'documentAssembly'
		| 'printing'
		| 'highResolutionPrinting';
	export const PermissionsEnum = {
		DisallowAll: 'disallowAll' as PermissionsEnum,
		AllowAll: 'allowAll' as PermissionsEnum,
		ContentCopy: 'contentCopy' as PermissionsEnum,
		ContentCopyForAccessibility: 'contentCopyForAccessibility' as PermissionsEnum,
		ModifyContents: 'modifyContents' as PermissionsEnum,
		ModifyAnnotations: 'modifyAnnotations' as PermissionsEnum,
		FillIn: 'fillIn' as PermissionsEnum,
		DocumentAssembly: 'documentAssembly' as PermissionsEnum,
		Printing: 'printing' as PermissionsEnum,
		HighResolutionPrinting: 'highResolutionPrinting' as PermissionsEnum
	}
}
