/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DocGenSettingsResultChartData} from './docGenSettingsResultChartData';
import {DocGenSettingsResultHtml} from './docGenSettingsResultHtml';
import {DocGenSettingsResultImage} from './docGenSettingsResultImage';
import {DocGenSettingsResultOdt} from './docGenSettingsResultOdt';
import {DocGenSettingsResultOoxml} from './docGenSettingsResultOoxml';
import {DocGenSettingsResultPdf} from './docGenSettingsResultPdf';
import {DocGenSettingsResultText} from './docGenSettingsResultText';


export interface DocGenSettingsResult {
	content?: DocGenSettingsResult.ContentEnum;
	chartData?: DocGenSettingsResultChartData;
	format?: DocGenSettingsResult.FormatEnum;
	ooxml?: DocGenSettingsResultOoxml;
	image?: DocGenSettingsResultImage;
	pdf?: DocGenSettingsResultPdf;
	html?: DocGenSettingsResultHtml;
	text?: DocGenSettingsResultText;
	odt?: DocGenSettingsResultOdt;
}
export namespace DocGenSettingsResult {
	export type ContentEnum = 'returnContent' | 'storeContent' | 'storeAndReturnContent' | 'noStoreNoReturn';
	export const ContentEnum = {
		ReturnContent: 'returnContent' as ContentEnum,
		StoreContent: 'storeContent' as ContentEnum,
		StoreAndReturnContent: 'storeAndReturnContent' as ContentEnum,
		NoStoreNoReturn: 'noStoreNoReturn' as ContentEnum
	};
	export type FormatEnum = 'ooxml' | 'pdf' | 'html' | 'text' | 'xps' | 'odt' | 'rtf' | 'image';
	export const FormatEnum = {
		Ooxml: 'ooxml' as FormatEnum,
		Pdf: 'pdf' as FormatEnum,
		Html: 'html' as FormatEnum,
		Text: 'text' as FormatEnum,
		Xps: 'xps' as FormatEnum,
		Odt: 'odt' as FormatEnum,
		Rtf: 'rtf' as FormatEnum,
		Image: 'image' as FormatEnum
	};
}
