/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentPostProcessing } from './documentPostProcessing';
import { FlowExecution } from './flowExecution';
import { IdWithName } from './idWithName';
import { ObjectUsage } from './objectUsage';


export interface Document {
    id?: string;
    displayName?: string;
    description?: string;
    createdAt?: string;
    createdBy?: IdWithName;
    modifiedAt?: string;
    modifiedBy?: IdWithName;
    templateId?: IdWithName;
    language?: IdWithName;
    origin?: IdWithName;
    finished?: boolean;
    expiration?: string;
    contentType?: string;
    postProcessing?: Array<DocumentPostProcessing>;
    usage?: ObjectUsage;
    flowExecution?: FlowExecution;
}
