/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {EntityDefinitionLookups} from './entityDefinitionLookups';
import {EntityDefinitionRelationships} from './entityDefinitionRelationships';
import {EntityField} from './entityField';


export interface EntityDefinition {
	name?: string;
	displayName?: string;
	description?: string;
	canBePrimary?: boolean;
	fields?: Array<EntityField>;
	lookups?: Array<EntityDefinitionLookups>;
	relationships?: Array<EntityDefinitionRelationships>;
}
