/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExpressionFunctionArguments {
    name?: string;
    type?: ExpressionFunctionArguments.TypeEnum;
    optional?: boolean;
    helpLink?: string;
    defaultValue?: string;
}
export namespace ExpressionFunctionArguments {
    export type TypeEnum = 'notSpecified' | 'period' | 'date' | 'time' | 'dateTime' | 'number' | 'text' | 'boolean' | 'pattern' | 'datePattern' | 'timePattern' | 'dateTimePattern' | 'textWithExtendedCharacters' | 'regEx' | 'regExSubstitution' | 'locale' | 'durationPattern' | 'decimalPattern';
    export const TypeEnum = {
        NotSpecified: 'notSpecified' as TypeEnum,
        Period: 'period' as TypeEnum,
        Date: 'date' as TypeEnum,
        Time: 'time' as TypeEnum,
        DateTime: 'dateTime' as TypeEnum,
        Number: 'number' as TypeEnum,
        Text: 'text' as TypeEnum,
        Boolean: 'boolean' as TypeEnum,
        Pattern: 'pattern' as TypeEnum,
        DatePattern: 'datePattern' as TypeEnum,
        TimePattern: 'timePattern' as TypeEnum,
        DateTimePattern: 'dateTimePattern' as TypeEnum,
        TextWithExtendedCharacters: 'textWithExtendedCharacters' as TypeEnum,
        RegEx: 'regEx' as TypeEnum,
        RegExSubstitution: 'regExSubstitution' as TypeEnum,
        Locale: 'locale' as TypeEnum,
        DurationPattern: 'durationPattern' as TypeEnum,
        DecimalPattern: 'decimalPattern' as TypeEnum
    }
}
