/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FilterCondition {
	key?: string;
	operator?: FilterCondition.OperatorEnum;
	values?: Array<any>;
}
export namespace FilterCondition {
	export type OperatorEnum =
		'between'
		| 'notBetween'
		| 'equalTo'
		| 'notEqualTo'
		| 'like'
		| 'notLike'
		| 'greaterThan'
		| 'lessThan'
		| 'greaterThanOrEqualTo'
		| 'lessThanOrEqualTo'
		| 'isTrue'
		| 'isFalse'
		| 'isBlank'
		| 'notIsBlank'
		| 'in'
		| 'isNull'
		| 'isNotNull';
	export const OperatorEnum = {
		Between: 'between' as OperatorEnum,
		NotBetween: 'notBetween' as OperatorEnum,
		EqualTo: 'equalTo' as OperatorEnum,
		NotEqualTo: 'notEqualTo' as OperatorEnum,
		Like: 'like' as OperatorEnum,
		NotLike: 'notLike' as OperatorEnum,
		GreaterThan: 'greaterThan' as OperatorEnum,
		LessThan: 'lessThan' as OperatorEnum,
		GreaterThanOrEqualTo: 'greaterThanOrEqualTo' as OperatorEnum,
		LessThanOrEqualTo: 'lessThanOrEqualTo' as OperatorEnum,
		IsTrue: 'isTrue' as OperatorEnum,
		IsFalse: 'isFalse' as OperatorEnum,
		IsBlank: 'isBlank' as OperatorEnum,
		NotIsBlank: 'notIsBlank' as OperatorEnum,
		In: 'in' as OperatorEnum,
		IsNull: 'isNull' as OperatorEnum,
		IsNotNull: 'isNotNull' as OperatorEnum
	};
}
