/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FlowStep {
	id: string;
	displayName: string;
	description?: string;
	iconClass?: string;
	group?: string;
	type?: FlowStep.TypeEnum;
	primaryParameters?: Array<string>;
	inputSchema?: any;
	inputForm?: Array<any>;
	outputId?: string;
	externalOutputParameters?: Array<string>;
	outputSchema?: any;
}
export namespace FlowStep {
	export type TypeEnum = 'data' | 'gendoc' | 'convert' | 'postprocess' | 'other';
	export const TypeEnum = {
		Data: 'data' as TypeEnum,
		Gendoc: 'gendoc' as TypeEnum,
		Convert: 'convert' as TypeEnum,
		Postprocess: 'postprocess' as TypeEnum,
		Other: 'other' as TypeEnum
	};
}
