/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlowExecutionIteration } from './flowExecutionIteration';
import { FlowExecutionStage } from './flowExecutionStage';
import { FlowExecutionStateOutput } from './flowExecutionStateOutput';
import { FlowZoneState } from './flowZoneState';
import { IdWithName } from './idWithName';


export interface FlowExecutionState {
    inputData?: IdWithName;
    output?: FlowExecutionStateOutput;
    stages?: Array<FlowExecutionStage>;
    /**
     * if the input supports multiple iterations, these are the iterations
     */
    iterations?: Array<FlowExecutionIteration>;
    /**
     * if the input supports multiple iterations, but groupToSingleDocument is enabled, these are the post processing zones. If the input does not support multiple iterations, these are the flow zones
     */
    report?: Array<FlowZoneState>;
    waitingFor?: string;
}
