/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FlowDoStepState {
    start?: string;
    end?: string;
    status?: FlowDoStepState.StatusEnum;
    input?: any;
    output?: any;
}
export namespace FlowDoStepState {
    export type StatusEnum = 'Output' | 'Error' | 'Waiting' | 'UserInput' | 'Skipped';
    export const StatusEnum = {
        Output: 'Output' as StatusEnum,
        Error: 'Error' as StatusEnum,
        Waiting: 'Waiting' as StatusEnum,
        UserInput: 'UserInput' as StatusEnum,
        Skipped: 'Skipped' as StatusEnum
    }
}
