/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {FlowConditionState} from './flowConditionState';
import {FlowDoStepState} from './flowDoStepState';
import {FlowSwitchState} from './flowSwitchState';
import {FlowTryState} from './flowTryState';


export interface FlowBlockState {
	id?: string;
	displayName?: string;
	step?: FlowDoStepState;
	condition?: FlowConditionState;
	try?: FlowTryState;
	switch?: FlowSwitchState;
}
