/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type FlowExecutionStatus =
	'Queued'
	| 'Running'
	| 'Waiting'
	| 'UserInput'
	| 'Success'
	| 'Error'
	| 'Canceled'
	| 'SelectFlow'
	| 'Interrupted';

export const FlowExecutionStatus = {
	Queued: 'Queued' as FlowExecutionStatus,
	Running: 'Running' as FlowExecutionStatus,
	Waiting: 'Waiting' as FlowExecutionStatus,
	UserInput: 'UserInput' as FlowExecutionStatus,
	Success: 'Success' as FlowExecutionStatus,
	Error: 'Error' as FlowExecutionStatus,
	Canceled: 'Canceled' as FlowExecutionStatus,
	SelectFlow: 'SelectFlow' as FlowExecutionStatus,
	Interrupted: 'Interrupted' as FlowExecutionStatus
}
