/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {FlowCondition} from './flowCondition';
import {FlowDoStep} from './flowDoStep';
import {FlowSwitch} from './flowSwitch';
import {FlowTry} from './flowTry';


export interface FlowBlock {
	id?: string;
	displayName?: string;
	outputParameters?: Array<string>;
	step?: FlowDoStep;
	condition?: FlowCondition;
	try?: FlowTry;
	switch?: FlowSwitch;
}
