/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {FlowExecutionProgress} from './flowExecutionProgress';


/**
 * A part in an execution where the flow was actually running
 */
export interface FlowExecutionStage {
	start?: string;
	end?: string;
	input?: any;
	lastProgress?: FlowExecutionProgress;
}
