/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {FlowExecutionOutput} from './flowExecutionOutput';
import {FlowExecutionState} from './flowExecutionState';
import {FlowExecutionStatus} from './flowExecutionStatus';
import {IdWithName} from './idWithName';


export interface FlowExecution {
	id?: string;
	createdAt?: string;
	createdBy?: IdWithName;
	createdFor?: IdWithName;
	modifiedAt?: string;
	modifiedBy?: IdWithName;
	status?: FlowExecutionStatus;
	flow?: IdWithName;
	state?: FlowExecutionState;
	mode?: FlowExecution.ModeEnum;
	outputs?: Array<FlowExecutionOutput>;
}
export namespace FlowExecution {
	export type ModeEnum = 'interactive' | 'batch';
	export const ModeEnum = {
		Interactive: 'interactive' as ModeEnum,
		Batch: 'batch' as ModeEnum
	};
}
