/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {FlowBody} from './flowBody';
import {FlowInput} from './flowInput';
import {FlowOutput} from './flowOutput';
import {FlowSettings} from './flowSettings';
import {IdWithName} from './idWithName';
import {TagGroupRef} from './tagGroupRef';


export interface Flow {
	id?: string;
	displayName?: string;
	description?: string;
	createdAt?: string;
	createdBy?: IdWithName;
	modifiedAt?: string;
	modifiedBy?: IdWithName;
	tagGroups?: Array<TagGroupRef>;
	type?: Flow.TypeEnum;
	body?: FlowBody;
	input?: FlowInput;
	primaryEntity?: string;
	primaryTemplate?: IdWithName;
	outputs?: Array<FlowOutput>;
	settings?: FlowSettings;
}
export namespace Flow {
	export type TypeEnum = 'simple' | 'advanced';
	export const TypeEnum = {
		Simple: 'simple' as TypeEnum,
		Advanced: 'advanced' as TypeEnum
	};
}
