/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GcpPrintProps {
	duplexing?: GcpPrintProps.DuplexingEnum;
	collate?: GcpPrintProps.CollateEnum;
	color?: GcpPrintProps.ColorEnum;
	orientation?: GcpPrintProps.OrientationEnum;
	vendorCapabilities?: Array<{ [key: string]: string; }>;
}
export namespace GcpPrintProps {
	export type DuplexingEnum = 'default' | 'noDuplex' | 'longEdge' | 'shortEdge';
	export const DuplexingEnum = {
		Default: 'default' as DuplexingEnum,
		NoDuplex: 'noDuplex' as DuplexingEnum,
		LongEdge: 'longEdge' as DuplexingEnum,
		ShortEdge: 'shortEdge' as DuplexingEnum
	};
	export type CollateEnum = 'default' | 'true' | 'false';
	export const CollateEnum = {
		Default: 'default' as CollateEnum,
		True: 'true' as CollateEnum,
		False: 'false' as CollateEnum
	};
	export type ColorEnum = 'default' | 'auto' | 'standardColor' | 'standardMonochrome' | 'customColor' | 'customMonochrome';
	export const ColorEnum = {
		Default: 'default' as ColorEnum,
		Auto: 'auto' as ColorEnum,
		StandardColor: 'standardColor' as ColorEnum,
		StandardMonochrome: 'standardMonochrome' as ColorEnum,
		CustomColor: 'customColor' as ColorEnum,
		CustomMonochrome: 'customMonochrome' as ColorEnum
	};
	export type OrientationEnum = 'default' | 'auto' | 'portrait' | 'landscape';
	export const OrientationEnum = {
		Default: 'default' as OrientationEnum,
		Auto: 'auto' as OrientationEnum,
		Portrait: 'portrait' as OrientationEnum,
		Landscape: 'landscape' as OrientationEnum
	};
}
