/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GcpVendorCapabilityTypedValue {
    type?: GcpVendorCapabilityTypedValue.TypeEnum;
}
export namespace GcpVendorCapabilityTypedValue {
    export type TypeEnum = 'boolean' | 'float' | 'integer' | 'string';
    export const TypeEnum = {
        Boolean: 'boolean' as TypeEnum,
        Float: 'float' as TypeEnum,
        Integer: 'integer' as TypeEnum,
        String: 'string' as TypeEnum
    }
}
