/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GcpVendorCapabilityRange {
    type?: GcpVendorCapabilityRange.TypeEnum;
    default?: string;
    min?: string;
    max?: string;
}
export namespace GcpVendorCapabilityRange {
    export type TypeEnum = 'float' | 'integer';
    export const TypeEnum = {
        Float: 'float' as TypeEnum,
        Integer: 'integer' as TypeEnum
    }
}
