/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeneratedDocumentCharts } from './generatedDocumentCharts';
import { GeneratedDocumentContent } from './generatedDocumentContent';
import { GeneratedDocumentPages } from './generatedDocumentPages';
import { GeneratedDocumentProperties } from './generatedDocumentProperties';
import { IdWithName } from './idWithName';
import { StatusMessage } from './statusMessage';


export interface GeneratedDocument {
    displayName?: string;
    createdAt?: string;
    createdBy?: IdWithName;
    properties?: GeneratedDocumentProperties;
    content?: GeneratedDocumentContent;
    pages?: Array<GeneratedDocumentPages>;
    charts?: Array<GeneratedDocumentCharts>;
    messages?: Array<StatusMessage>;
}
