/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Archive } from './archive';
import { ConnectorType } from './connectorType';
import { IdWithName } from './idWithName';
import { ImportInformationMissingConnectors } from './importInformationMissingConnectors';
import { MultiDependencyMapping } from './multiDependencyMapping';


export interface ImportInformation {
    archive?: Archive;
    topLevelItems?: Array<IdWithName>;
    suggestedMappings?: Array<MultiDependencyMapping>;
    missingConnectors?: Array<ImportInformationMissingConnectors>;
    missingConnectorTypes?: Array<ConnectorType>;
}
