/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface JpsPrintProps {
    duplexing?: JpsPrintProps.DuplexingEnum;
    collate?: JpsPrintProps.CollateEnum;
    chromaticity?: JpsPrintProps.ChromaticityEnum;
    orientation?: JpsPrintProps.OrientationEnum;
    paperSource?: string;
    firstPagePaperSource?: string;
    paperSize?: string;
}
export namespace JpsPrintProps {
    export type DuplexingEnum = 'default' | 'oneSided' | 'twoSidedLongEdge' | 'twoSidedShortEdge';
    export const DuplexingEnum = {
        Default: 'default' as DuplexingEnum,
        OneSided: 'oneSided' as DuplexingEnum,
        TwoSidedLongEdge: 'twoSidedLongEdge' as DuplexingEnum,
        TwoSidedShortEdge: 'twoSidedShortEdge' as DuplexingEnum
    }
    export type CollateEnum = 'default' | 'true' | 'false';
    export const CollateEnum = {
        Default: 'default' as CollateEnum,
        True: 'true' as CollateEnum,
        False: 'false' as CollateEnum
    }
    export type ChromaticityEnum = 'default' | 'monochrome' | 'color';
    export const ChromaticityEnum = {
        Default: 'default' as ChromaticityEnum,
        Monochrome: 'monochrome' as ChromaticityEnum,
        Color: 'color' as ChromaticityEnum
    }
    export type OrientationEnum = 'default' | 'portrait' | 'landscape';
    export const OrientationEnum = {
        Default: 'default' as OrientationEnum,
        Portrait: 'portrait' as OrientationEnum,
        Landscape: 'landscape' as OrientationEnum
    }
}
