/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FormatDefinition } from './formatDefinition';
import { LanguageDefinitionDateTimeFormats } from './languageDefinitionDateTimeFormats';
import { LanguageDefinitionNumberFormat } from './languageDefinitionNumberFormat';


export interface LanguageDefinition {
    /**
     * The language code
     */
    id: string;
    displayName: string;
    displayCountry?: string;
    displayLanguage?: string;
    isSystem?: boolean;
    dateTimeFormats?: LanguageDefinitionDateTimeFormats;
    periodFormats?: Array<FormatDefinition>;
    numberFormat?: LanguageDefinitionNumberFormat;
}
