/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {LicenseInformationLimits} from './licenseInformationLimits';
import {LicenseInformationPlugins} from './licenseInformationPlugins';


export interface LicenseInformation {
	id?: string;
	displayName?: string;
	edition?: string;
	flavour?: string;
	expiry?: string;
	valid?: boolean;
	expired?: boolean;
	limits?: LicenseInformationLimits;
	plugins?: Array<LicenseInformationPlugins>;
}
