/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LicenseInformationLimitsDocuments { 
    max?: number;
    interval?: LicenseInformationLimitsDocuments.IntervalEnum;
    used?: number;
    since?: string;
}
export namespace LicenseInformationLimitsDocuments {
    export type IntervalEnum = 'year' | 'month';
    export const IntervalEnum = {
        Year: 'year' as IntervalEnum,
        Month: 'month' as IntervalEnum
    };
}
