/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Notification {
	id?: string;
	message?: string;
	key?: string;
	severity?: Notification.TypeEnum;
	targetRoles?: Array<string>;
}
export namespace Notification {
	export type TypeEnum = 'info' | 'warning' | 'critical' | 'fatal';
	export const TypeEnum = {
		Info: 'info' as TypeEnum,
		Warning: 'warning' as TypeEnum,
		Critical: 'critical' as TypeEnum,
		Fatal: 'fatal' as TypeEnum
	};
}
