/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ConditionValue} from './conditionValue';


export interface NumberCondition {
	operator?: NumberCondition.OperatorEnum;
	value1?: ConditionValue;
	value2?: ConditionValue;
	valueFormat?: string;
}
export namespace NumberCondition {
	export type OperatorEnum = 'between' | 'notBetween' | 'equalTo' | 'notEqualTo' | 'greaterThan' | 'lessThan' | 'greaterThanOrEqualTo' | 'lessThanOrEqualTo';
	export const OperatorEnum = {
		Between: 'between' as OperatorEnum,
		NotBetween: 'notBetween' as OperatorEnum,
		EqualTo: 'equalTo' as OperatorEnum,
		NotEqualTo: 'notEqualTo' as OperatorEnum,
		GreaterThan: 'greaterThan' as OperatorEnum,
		LessThan: 'lessThan' as OperatorEnum,
		GreaterThanOrEqualTo: 'greaterThanOrEqualTo' as OperatorEnum,
		LessThanOrEqualTo: 'lessThanOrEqualTo' as OperatorEnum
	};
}
