/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ObjectUsage = 'flowExecutionInput' | 'flowExecutionInternal' | 'flowExecutionOutput' | 'userCreated';

export const ObjectUsage = {
    FlowExecutionInput: 'flowExecutionInput' as ObjectUsage,
    FlowExecutionInternal: 'flowExecutionInternal' as ObjectUsage,
    FlowExecutionOutput: 'flowExecutionOutput' as ObjectUsage,
    UserCreated: 'userCreated' as ObjectUsage
}
