/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ObjectType =
	'asset'
	| 'connector'
	| 'connectorType'
	| 'datasource'
	| 'data'
	| 'dataset'
	| 'document'
	| 'entityReference'
	| 'flow'
	| 'language'
	| 'printer'
	| 'tag'
	| 'tagGroup'
	| 'template'
	| 'templateLibrary'
	| 'user';

export const ObjectType = {
	Asset: 'asset' as ObjectType,
	Connector: 'connector' as ObjectType,
	ConnectorType: 'connectorType' as ObjectType,
	Datasource: 'datasource' as ObjectType,
	Data: 'data' as ObjectType,
	Dataset: 'dataset' as ObjectType,
	Document: 'document' as ObjectType,
	EntityReference: 'entityReference' as ObjectType,
	Flow: 'flow' as ObjectType,
	Language: 'language' as ObjectType,
	Printer: 'printer' as ObjectType,
	Tag: 'tag' as ObjectType,
	TagGroup: 'tagGroup' as ObjectType,
	Template: 'template' as ObjectType,
	TemplateLibrary: 'templateLibrary' as ObjectType,
	User: 'user' as ObjectType
};
