/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusMessage } from './statusMessage';


export interface OperationStatus {
    status?: OperationStatus.StatusEnum;
    hasWarnings?: boolean;
    messages?: Array<StatusMessage>;
}
export namespace OperationStatus {
    export type StatusEnum = 'successful' | 'failed';
    export const StatusEnum = {
        Successful: 'successful' as StatusEnum,
        Failed: 'failed' as StatusEnum
    }
}
