/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConditionGroup } from './conditionGroup';


export interface Part {
    template: string;
    /**
     * Read-only, will contain the displayName of the linked template at the moment of retrieval
     */
    templateDisplayName?: string;
    type: Part.TypeEnum;
    break?: Part.ModelBreakEnum;
    linkHeaders?: boolean;
    occurrence?: Part.OccurrenceEnum;
    conditions?: ConditionGroup;
}
export namespace Part {
    export type TypeEnum = 'body' | 'header' | 'footer' | 'addition';
    export const TypeEnum = {
        Body: 'body' as TypeEnum,
        Header: 'header' as TypeEnum,
        Footer: 'footer' as TypeEnum,
        Addition: 'addition' as TypeEnum
    }
    export type ModelBreakEnum = 'none' | 'continuous' | 'newColumn' | 'newPage' | 'evenPage' | 'oddPage';
    export const ModelBreakEnum = {
        None: 'none' as ModelBreakEnum,
        Continuous: 'continuous' as ModelBreakEnum,
        NewColumn: 'newColumn' as ModelBreakEnum,
        NewPage: 'newPage' as ModelBreakEnum,
        EvenPage: 'evenPage' as ModelBreakEnum,
        OddPage: 'oddPage' as ModelBreakEnum
    }
    export type OccurrenceEnum = 'primary' | 'firstPage' | 'evenPage';
    export const OccurrenceEnum = {
        Primary: 'primary' as OccurrenceEnum,
        FirstPage: 'firstPage' as OccurrenceEnum,
        EvenPage: 'evenPage' as OccurrenceEnum
    }
}
