/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GcpVendorCapability } from './gcpVendorCapability';
import { IdWithName } from './idWithName';


export interface PrinterDefinitionPrinterInfoGcp {
    connector?: IdWithName;
    createTime?: string;
    updateTime?: string;
    accessTime?: string;
    connectionStatus?: PrinterDefinitionPrinterInfoGcp.ConnectionStatusEnum;
    vendorCapabilities?: Array<GcpVendorCapability>;
}
export namespace PrinterDefinitionPrinterInfoGcp {
    export type ConnectionStatusEnum = 'unknown' | 'online' | 'offline' | 'dormant';
    export const ConnectionStatusEnum = {
        Unknown: 'unknown' as ConnectionStatusEnum,
        Online: 'online' as ConnectionStatusEnum,
        Offline: 'offline' as ConnectionStatusEnum,
        Dormant: 'dormant' as ConnectionStatusEnum
    }
}
