/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrinterDefinitionPrinterInfo } from './printerDefinitionPrinterInfo';


export interface PrinterDefinition {
    id?: string;
    displayName: string;
    description?: string;
    flavor: PrinterDefinition.FlavorEnum;
    printerInfo?: PrinterDefinitionPrinterInfo;
}
export namespace PrinterDefinition {
    export type FlavorEnum = 'jps' | 'gcp';
    export const FlavorEnum = {
        Jps: 'jps' as FlavorEnum,
        Gcp: 'gcp' as FlavorEnum
    }
}
