/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {IdWithName} from './idWithName';
import {PrinterProperties} from './printerProperties';


export interface Printer {
	id?: string;
	displayName: string;
	description?: string;
	createdAt?: string;
	createdBy?: IdWithName;
	modifiedAt?: string;
	modifiedBy?: IdWithName;
	definition: IdWithName;
	flavor?: Printer.FlavorEnum;
	defaultPrinter?: boolean;
	properties?: PrinterProperties;
}
export namespace Printer {
	export type FlavorEnum = 'jps' | 'gcp';
	export const FlavorEnum = {
		Jps: 'jps' as FlavorEnum,
		Gcp: 'gcp' as FlavorEnum
	};
}
