/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PseudoElementInformation {
	id?: string;
	displayName?: string;
	type?: PseudoElementInformation.TypeEnum;
}

export namespace PseudoElementInformation {
	export type TypeEnum = 'field' | 'relation';
	export const TypeEnum = {
		Field: 'field' as TypeEnum,
		Relation: 'relation' as TypeEnum
	}
}
