/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {CleanupSettings} from './cleanupSettings';
import {DefaultPluginSettings} from './defaultPluginSettings';
import {OnCreateSettings} from './onCreateSettings';
import {ProjectSettings} from './projectSettings';
import {UserManagementSettings} from './userManagementSettings';


export interface Settings {
	project?: ProjectSettings;
	defaultPlugin?: DefaultPluginSettings;
	cleanup?: CleanupSettings;
	userManagement?: UserManagementSettings;
	onCreate?: OnCreateSettings;
	frontend?: any;
}
