/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SchemaContent } from './schemaContent';


export interface StandardTemplateDefinition {
    content?: string;
    datasets?: Array<string>;
    schemas?: Array<SchemaContent>;
}
