/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {StatisticsPerObject} from './statisticsPerObject';
import {StatisticsPerTime} from './statisticsPerTime';
import {StatisticsPerUser} from './statisticsPerUser';


export interface Statistics {
	perTime?: Array<StatisticsPerTime>;
	perObject?: Array<StatisticsPerObject>;
	perUser?: Array<StatisticsPerUser>;
}
