/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusMessageDocumentLocation } from './statusMessageDocumentLocation';


export interface StatusMessage {
    code?: string;
    message?: string;
    type?: StatusMessage.TypeEnum;
    documentLocation?: StatusMessageDocumentLocation;
}
export namespace StatusMessage {
    export type TypeEnum = 'info' | 'warning' | 'error';
    export const TypeEnum = {
        Info: 'info' as TypeEnum,
        Warning: 'warning' as TypeEnum,
        Error: 'error' as TypeEnum
    }
}
