/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemInfoDefaults } from './systemInfoDefaults';


export interface SystemInfo {
    version?: string;
    displayName?: string;
    description?: string;
    role?: SystemInfo.RoleEnum;
    defaults?: SystemInfoDefaults;
    rssFeed?: string;
    supportUrl?: string;
    assetsUrl?: string;
}
export namespace SystemInfo {
    export type RoleEnum = 'sandbox' | 'development' | 'testing' | 'production';
    export const RoleEnum = {
        Sandbox: 'sandbox' as RoleEnum,
        Development: 'development' as RoleEnum,
        Testing: 'testing' as RoleEnum,
        Production: 'production' as RoleEnum
    }
}
