/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdWithName } from './idWithName';


/**
 * A tag group is a group of tags which allows to filter objects (flow, template, ...)
 */
export interface TagGroup {
    id?: string;
    displayName?: string;
    description?: string;
    createdAt?: string;
    createdBy?: IdWithName;
    modifiedAt?: string;
    modifiedBy?: IdWithName;
    /**
     * All possible tags for a group
     */
    tags?: Array<string>;
    definedBy?: TagGroup.DefinedByEnum;
}
export namespace TagGroup {
    export type DefinedByEnum = 'user' | 'system';
    export const DefinedByEnum = {
        User: 'user' as DefinedByEnum,
        System: 'system' as DefinedByEnum
    }
}
