/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {IdWithName} from './idWithName';


/**
 * The selected tags for a tag group for an object (flow, template, ...)
 */
export interface TagGroupRef {
	group?: IdWithName;
	/**
	 * The selected tags for a tag group for an object
	 */
	tags?: Array<string>;
}
