/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The content of the template when type is standard. Content of composed templates is embedded in the template definition below composedContent
 */
export interface TemplateStandardContent {
	supportedLanguages?: Array<string>;
	/**
	 * Link to the endpoint that returns the content of the template
	 */
	link?: string;
}
