/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {IdWithName} from './idWithName';
import {TagGroupRef} from './tagGroupRef';
import {TemplateComposedContent} from './templateComposedContent';
import {TemplateDatasets} from './templateDatasets';
import {TemplateStandardContent} from './templateStandardContent';


export interface Template {
	id?: string;
	displayName: string;
	description?: string;
	createdAt?: string;
	createdBy?: IdWithName;
	modifiedAt?: string;
	modifiedBy?: IdWithName;
	datasets?: Array<TemplateDatasets>;
	type?: Template.TypeEnum;
	tagGroups?: Array<TagGroupRef>;
	standardContent?: TemplateStandardContent;
	composedContent?: TemplateComposedContent;
}

export namespace Template {
	export type TypeEnum = 'standard' | 'composed' | 'portal';
	export const TypeEnum = {
		Standard: 'standard' as TypeEnum,
		Composed: 'composed' as TypeEnum ,
		Portal: 'portal' as TypeEnum
	}
}
