/**
 * XperiDo
 * This describes the REST api for one XperiDo project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConditionValue } from './conditionValue';


export interface TextCondition {
    operator?: TextCondition.OperatorEnum;
    value1?: ConditionValue;
    value2?: ConditionValue;
}
export namespace TextCondition {
    export type OperatorEnum = 'contains' | 'notContains' | 'equalTo' | 'notEqualTo' | 'isBlank' | 'notIsBlank';
    export const OperatorEnum = {
        Contains: 'contains' as OperatorEnum,
        NotContains: 'notContains' as OperatorEnum,
        EqualTo: 'equalTo' as OperatorEnum,
        NotEqualTo: 'notEqualTo' as OperatorEnum,
        IsBlank: 'isBlank' as OperatorEnum,
        NotIsBlank: 'notIsBlank' as OperatorEnum
    }
}
