/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {IdWithName} from './idWithName';
import {Role} from './role';
import {UserIdentity} from './userIdentity';


export interface User {
	id?: string;
	userName: string;
	displayName?: string;
	firstName: string;
	lastName: string;
	description?: string;
	emailAddress: string;
	createdAt?: string;
	createdBy?: IdWithName;
	modifiedAt?: string;
	modifiedBy?: IdWithName;
	lastLogin?: string;
	loginCount?: number;
	active?: boolean;
	identity?: UserIdentity;
	settings?: any;
	roles?: Array<Role>;
}
