/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {UserIdentityExternal} from './userIdentityExternal';
import {UserIdentityNative} from './userIdentityNative';


export interface UserIdentity {
	type?: UserIdentity.TypeEnum;
	native?: UserIdentityNative;
	external?: UserIdentityExternal;
}

export namespace UserIdentity {
	export type TypeEnum = 'native' | 'external' | 'none';
	export const TypeEnum = {
		Native: 'native' as TypeEnum,
		External: 'external' as TypeEnum,
		None: 'none' as TypeEnum
	}
}
