/**
 * XperiDo
 * This describes the REST api for one XperiDo project
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {IdWithName} from './idWithName';


export interface Version {
	id?: string;
	/**
	 * The comments entered when creating the version
	 */
	description?: string;
	createdAt?: string;
	createdBy?: IdWithName;
	/**
	 * Increments with one each time a new version is created
	 */
	revision?: number;
}
